### ISSUE TITLE
Require turboboost doesn't work from Rubygems

### ISSUE THREAD

**Issue by bmorrall** [waymondo/turboboost#13]
I updated my app to use `turboboost 0.0.12` and noticed that `//= require turboboost/turboboost` was failing.

The required files are on master, could we get another point release soon? Do you have any major issues preventing this, that I can go over in the meantime?

**Comment by waymondo** [comment]
Thanks for this, I am in the midst of making a few changes. Once things setting down, I will publish `0.1.0` within the next few days. For now, you can point to Github for the most recent.
