### ISSUE TITLE
Execute XHR Request n times

### ISSUE THREAD

**Issue by patricklehmann** [waymondo/turboboost#14]
Hi guys,

After adding turboboost everything works fine: Now i can submit my forms over xhr and let redirect it with turbolinks. After redoing it n times it will send my form n+1 times to the resource. have anyone an idea?

= simple_form_for [:backend, resource ], turboboost: true, html: { role: :form } do |f|

 = require jquery
 = require jquery_ujs
 = require turbolinks
 = require turboboost

**Comment by cyanpunk** [comment]
Confirmed, same issue for me. I have 5 post page sequence, and at last everything is called 5x times.

**Comment by waymondo** [comment]
I just bumped the version and published `0.1.0` to Rubygems. Can you test and let me know if your issue still exists? If it does, can I get more information about what steps I can do to reproduce? Any other notable assets/gems to mention?

**Comment by cyanpunk** [comment]
This occurs when putting application scripts in body instead of `head` tag.

In my project I had setup `requires` pre load in head tag, and `onLoad` stuff JS stuff to load in `body` tag, this was the problem, after moving everything to `head` turboboost stopped making n+1 requests on back-end.

**Comment by waymondo** [comment]
Yeah, that definitely sounds suspect. If you have the script with Turboboost within the `<body>` and `data-turbolinks-eval="false"` not set on that `<script>` tag, it would rebind the event listeners. @patricklehmann, is this the issue for you too?

**Comment by waymondo** [comment]
Closing due to no responses. Feel free to reopen and comment if there is still an issue here.
