### ISSUE TITLE
page:fetch triggered with normal links but not turboboost form

### ISSUE THREAD

**Issue by archonic** [waymondo/turboboost#5]
I've got some page transition animations which take advantage of turbolinks. Following normal links has the page:fetch event fire but it doesn't happen for my turboboosted form.

This is the JS that makes that happen:

    document.addEventListener('page:change', function() {
      document.getElementById('animate_wrapper').style.visibility = 'visible';
      document.getElementById('animate_wrapper').className += ' animated fadeInRight';
    });
    document.addEventListener('page:fetch', function() {
      document.getElementById('animate_wrapper').className += ' animated fadeOutLeft';
    });

The form I turboboosted is a surveyor form which has some of its own JS going on. Is there a way I can confirm if a form is taking advantage of turboboost?

**Comment by waymondo** [comment]
What version of rails are you using? Also, are you trying to do a GET request or POST request?

`page:fetch` is a Turbolinks event that currently isn't supported in Turboboost form-transformed Turbolinks requests, but I could see this being useful.

You can confirm a form is taking advantage of Turboboost in your Rails controller by making sure `request.headers['HTTP_X_TURBOBOOST']` is present.

**Comment by archonic** [comment]
I'm using rails 4.2 and the form is using a post request. It would be great to have `page:fetch` supported. Turbolinks with just a few lines of JS is providing a very hands-off way to animate every page load on a certain layout.

**Comment by waymondo** [comment]
Just spent some time looking at this and its working for me as I'd expect it. Here's my example controller action:

```
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

form markup:

```
<%= form_for @post, turboboost: true do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
```

and coffeescript:

```
document.addEventListener 'page:fetch', ->
  console.log('foo')
```

On a successful post create, the redirect is hit and is processed with Turboboost. Turboboost calls `Turbolinks.visit` on the returned redirect URL, which calls [fetchReplacement](https://github.com/rails/turbolinks/blob/master/lib/assets/javascripts/turbolinks.js.coffee#L52-L86) which fires `page:fetch`. `Turbolinks.visit` is also used for turboboost forms making GET requests, so all works there too.

If you aren't redirecting in your controller action with a POST request, then `page:fetch` isn't the right word to describe the event. You'd want to use `ajax:beforeSend` or `ajax:send` as I mentioned before.
